# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0571be0fd2b1b1229c0939a8845a802fb7299b57c32ce2ecf9ff754660f1867b915f461bbabd9c67faaced6df87b40352e5975f107bb65cbfe1836bca7b7cfe4

test:
  secret_key_base: 4df76539ae56a0de31b644a14f596f995ade4178f3188e4b1567832c6c8995e1717bd388c6fc4febbdd0436c63e1e919f9348e4218815e04e4ff1a49d8ba75c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
